### ISSUE TITLE
should_be_true raise exception for expression contains '=='

### ISSUE THREAD

**Issue by Time-Coder** [Time-Coder/PySimpleTest#1]
use version 1.0.6, run code `should_be_true(3 == 5)` will raise following exception:

```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    pst.should_be_true(3 == 5)
  File "...\site-packages\PySimpleTest\PySimpleTest.py", line 610, in should_be_true
    Fail("(" + str_args[0] + ") is False")
IndexError: list index out of range
```

**Comment by Time-Coder** [comment]
Fixed on version 1.0.7
